# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"DataBox": "core.ipynb"}

modules = ["core.py"]

doc_url = "//"

git_url = "https://github.com/limiteinductive/Databox/tree/main/"

def custom_doc_links(name): return None
