# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://limiteinductive.github.io/DataBox//"

git_url = "https://github.com/limiteinductive/Databox/tree/main/"

def custom_doc_links(name): return None
