# AUTOGENERATED! DO NOT EDIT! File to edit: core.ipynb (unless otherwise specified).

__all__ = ['DataBox']

# Cell
class DataBox:

    def __init__(self, block, getter, *tfms):

        self.block = tuplify(block)
        self.getter = getter
        self.tfms = tfms


    def __add__(self, other):
        pass
